# Generated by Django 5.0.7 on 2024-12-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riwayat_transaksi', '0002_rename_created_at_transactionhistory_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionhistory',
            name='brand',
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit'), ('Dompet Digital', 'Dompet Digital')], default='Cash', max_length=50),
        ),
    ]
