# Generated by Django 5.0.7 on 2024-12-15 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riwayat_transaksi', '0003_remove_transactionhistory_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('QRIS', 'QRIS')], default='Cash', max_length=50),
        ),
    ]
