# Generated by Django 5.0.7 on 2024-12-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riwayat_transaksi', '0004_alter_transactionhistory_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=50),
        ),
    ]
