# Generated by Django 5.0.7 on 2024-12-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riwayat_transaksi', '0005_transactionhistory_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='proof_of_payment',
            field=models.ImageField(blank=True, help_text='Upload proof for QRIS payments only.', null=True, upload_to='payment_proofs/'),
        ),
    ]
